#!/usr/bin/env python3
"""
gen_build.py — emit a build.ninja for a given architecture.

Usage:
    python3 tools/gen_build.py <arch>          # arch in {x86_64, aarch64}

Writes:
    build/<arch>/build.ninja

This is a stub. The full implementation will:
  - Read arch/<arch>/arch.toml for per-arch compile flags and triple.
  - Walk kernel/, userland/, arch/<arch>/ for source files.
  - Emit ninja rules for: compile C, compile asm, link kernel, link userland
    binaries, pack initramfs (mkcpio), and run codegen if schemas changed.
  - Honor environment overrides: CC, LD, AR, OBJCOPY, BUILD_TYPE (release|debug).

Output shape (sketch):

    cc_kernel = x86_64-elf-gcc
    cflags_kernel = -ffreestanding -nostdlib -nostartfiles \
                    -fno-builtin -fno-stack-protector -fno-pic -fno-pie \
                    -fno-omit-frame-pointer -Wall -Wextra -Wpedantic -Werror \
                    -std=c11 -mno-red-zone -O2 -g -Iuserland/libc/include

    rule cc_kern
      command = $cc_kernel $cflags_kernel -c $in -o $out -MMD -MF $out.d
      depfile = $out.d

    rule link_kern
      command = $cc_kernel -nostdlib -T arch/x86_64/kernel.ld -o $out $in

    build build/x86_64/kernel/main.o: cc_kern kernel/main.c
    build build/x86_64/kernel/sched/sched.o: cc_kern kernel/sched/sched.c
    ...
    build build/x86_64/kernel.elf: link_kern build/x86_64/kernel/main.o ...

    build build/x86_64/initramfs.cpio: mkcpio_pack <list-of-userland-binaries>

This file is fewer than 150 lines when complete.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ARCHES = ("x86_64", "aarch64")


def main(argv):
    if len(argv) != 2 or argv[1] not in ARCHES:
        print(f"usage: {argv[0]} <{ '|'.join(ARCHES) }>", file=sys.stderr)
        return 2

    arch = argv[1]
    build_dir = REPO / "build" / arch
    build_dir.mkdir(parents=True, exist_ok=True)

    # TODO: parse arch.toml, walk source tree, emit ninja rules.
    placeholder = f"""# DO NOT EDIT — generated by tools/gen_build.py for arch={arch}
# (stub — fill in real rules during v1 implementation)

ninja_required_version = 1.10

# arch    = {arch}
# build   = release

rule noop
  command = echo "build.ninja stub for {arch}; implement gen_build.py to populate"

build all: noop
default all
"""
    out = build_dir / "build.ninja"
    out.write_text(placeholder)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
